version: '3.6'
services:
  mysql:
    image: mysql:8.0.33
    environment:
      MYSQL_ROOT_PASSWORD: password
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=password --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 30s
      retries: 30
    volumes:
      - ./provision:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

  migrate:
    image: migrate/migrate
    volumes:
      - ./go-app/migrations:/migrations
    command: [ "-path", "/migrations", "-database",  "mysql://root:password@tcp(mysql:3306)/app", "up" ]
    depends_on:
      mysql:
        condition: service_healthy
    links:
      - mysql

  go-server:
    build:
      context: ./go-app
      dockerfile: ./Dockerfile
    environment:
      ADDRESS: "0.0.0.0:8081"
      MYSQL_URL: "root:password@tcp(mysql:3306)/app?parseTime=true"
    depends_on:
      - migrate
    ports:
      - "8081:8081"

volumes:
  mysql-data:
    driver: local
